// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

import (
	"time"
)

const TableNameEventList = "event_list"

// EventList mapped from table <event_list>
type EventList struct {
	ID        int32     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	UID       int32     `gorm:"column:uid;not null" json:"uid"`
	Tid       string    `gorm:"column:tid;not null;comment:事件的唯一标识" json:"tid"`           // 事件的唯一标识
	ImgURL    string    `gorm:"column:img_url;not null;comment:事件的图片" json:"img_url"`     // 事件的图片
	Title     string    `gorm:"column:title;not null;comment:事件的标题" json:"title"`         // 事件的标题
	Deadline  int32     `gorm:"column:deadline;not null;comment:事件的结束日期" json:"deadline"` // 事件的结束日期
	Desc      string    `gorm:"column:desc;not null;comment:事件的描述" json:"desc"`           // 事件的描述
	CreatedAt time.Time `gorm:"column:created_at" json:"created_at"`
	UpdatedAt time.Time `gorm:"column:updated_at" json:"updated_at"`
}

// TableName EventList's table name
func (*EventList) TableName() string {
	return TableNameEventList
}
