// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

import (
	"time"
)

const TableNameUser = "users"

// User mapped from table <users>
type User struct {
	ID         int32     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Username   string    `gorm:"column:username;not null;comment:用户名" json:"username"`       // 用户名
	Addr       string    `gorm:"column:addr;not null;comment:用户地址" json:"addr"`              // 用户地址
	InviteCode string    `gorm:"column:invite_code;not null;comment:邀请码" json:"invite_code"` // 邀请码
	CreatedAt  time.Time `gorm:"column:created_at" json:"created_at"`
	UpdatedAt  time.Time `gorm:"column:updated_at" json:"updated_at"`
	InviteUID  int32     `gorm:"column:invite_uid;not null;comment:邀请人uid" json:"invite_uid"` // 邀请人uid
}

// TableName User's table name
func (*User) TableName() string {
	return TableNameUser
}
