definitions:
  models.User:
    properties:
      addr:
        description: 用户地址
        type: string
      created_at:
        type: string
      id:
        type: integer
      invite_code:
        description: 邀请码
        type: string
      updated_at:
        type: string
      username:
        description: 用户名
        type: string
    type: object
info:
  contact: {}
paths:
  /users:
    get:
      consumes:
      - application/json
      description: 获取所有用户的信息
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.User'
      summary: 获取所有用户
      tags:
      - 用户管理
    post:
      consumes:
      - application/json
      parameters:
      - description: 用户名
        in: body
        name: username
        required: true
        schema:
          type: string
      - description: 用户地址
        in: body
        name: addr
        required: true
        schema:
          type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.User'
      summary: 创建一个新用户
      tags:
      - 用户管理
  /users/:id:
    get:
      consumes:
      - application/json
      description: 获取单个用户的信息
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.User'
      summary: 获取单个用户
      tags:
      - 用户管理
swagger: "2.0"
